const students = [{
        id: "1",
        name: "ABCD",
        course: "IC",
        level: 6,
        lesson: 4,
        points: 300,
        pendingLessons: 4,
        class: "6th",
        division: "A",
    },
    {
        id: "2",
        name: "PQRS",
        course: "PP",
        level: 6,
        lesson: 4,
        points: 350,
        class: "6th",
        division: "A",
        pendingLessons: 4,
        class: "6th",
        division: "B",
    },
    {
        id: "3",
        name: "POIU",
        course: "DS",
        level: 6,
        lesson: 4,
        points: 330,
        pendingLessons: 4,
        class: "7th",
        division: "A",
    },
    {
        id: "4",
        name: "VGFV",
        course: "DS",
        level: 6,
        lesson: 4,
        points: 290,
        pendingLessons: 4,
        class: "7th",
        division: "B",
    },
    {
        id: "5",
        name: "RTYY",
        course: "PP",
        level: 6,
        lesson: 4,
        points: 310,
        pendingLessons: 4,
        class: "6th",
        division: "A",
    },
    {
        id: "6",
        name: "RFGH",
        course: "IC",
        level: 6,
        lesson: 4,
        points: 305,
        pendingLessons: 4,
        class: "6th",
        division: "A",
    },
    {
        id: "7",
        name: "ABCD4545",
        course: "IC",
        level: 6,
        lesson: 4,
        points: 350,
        pendingLessons: 1,
        class: "8th",
        division: "B",
    },
    {
        id: "8",
        name: "PQRS48",
        course: "PP",
        level: 6,
        lesson: 4,
        points: 350,
        pendingLessons: 3,
        class: "7th",
        division: "B",
    },
    {
        id: "9",
        name: "POdawIU",
        course: "DS",
        level: 6,
        lesson: 4,
        points: 269,
        pendingLessons: 2,
        class: "8th",
        division: "A",
    },
    {
        id: "10",
        name: "VGdawFV",
        course: "DS",
        level: 6,
        lesson: 4,
        points: 298,
        pendingLessons: 8,
        class: "7th",
        division: "A",
    },
    {
        id: "11",
        name: "RdawdawdTYY",
        course: "PP",
        level: 6,
        lesson: 4,
        points: 290,
        pendingLessons: 4,
        class: "8th",
        division: "A",
    },
    {
        id: "12",
        name: "RawFGH",
        course: "IC",
        level: 6,
        lesson: 4,
        points: 325,
        pendingLessons: 1,
        class: "6th",
        division: "E",
    },
    {
        id: "13",
        name: "RawFdawGH",
        course: "IC",
        level: 6,
        lesson: 4,
        points: 325,
        pendingLessons: 1,
        class: "6th",
        division: "E",
    },
    {
        id: "14",
        name: "RawFGHdaw",
        course: "IC",
        level: 6,
        lesson: 4,
        points: 325,
        pendingLessons: 1,
        class: "6th",
        division: "E",
    },
    {
        id: "15",
        name: "RawFGdwaH",
        course: "IC",
        level: 6,
        lesson: 4,
        points: 325,
        pendingLessons: 1,
        class: "6th",
        division: "E",
    },
];


const schooldata = [
    {
        id:"1",
        name:"abcd",
        board:"state board",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Active"
    },
    {
        id:"2",
        name:"MIT",
        board:"cbse",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Active"
    },
    {
        id:"3",
        name:"PWE",
        board:"icse",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Active"
    },
    {
        id:"4",
        name:"7w97d9w",
        board:"icse",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Nearing validity"
    },
    {
        id:"5",
        name:"7ddwwddw",
        board:"icse",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Past validity"
    },
    {
        id:"6",
        name:"wddwd",
        board:"state board",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Past validity"
    },
    {
        id:"7",
        name:"dwdwd",
        board:"state board",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Past validity"
    },
    {
        id:"8",
        name:"dwd",
        board:"cbse",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Active"
    },
    {
        id:"9",
        name:"PWdwE",
        board:"icse",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Inactive"
    },
    {
        id:"10",
        name:"7w97dwd9w",
        board:"icse",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Nearing validity"
    },
    {
        id:"11",
        name:"7ddwwddw",
        board:"icse",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Inactive"
    },
    {
        id:"12",
        name:"wddwd",
        board:"state board",
        onboarded:"10 Jun 2021, 10:51 AM",
        licenceValidity: "10 Jun 2022",
        status: "Inactive"
    }
];

export default students;
export {schooldata};